package com.smu.csd.pokerivals.notification.dto;

public enum NotificationType {
    TOURNAMENT_PLAYER_INVITE,
    TOURNAMENT_ADMIN_REGISTRATION_CLOSED,
    MATCH_PLAYER_TIMING_CHANGE,
    MATCH_PLAYER_MATCH_OUTCOME,
    MATCH_PLAYER_FORFEIT,
    MATCH_ADMIN_CHANGE_TIME_AGREEMENT,
    MATCH_PLAYER_TIME_COMING,
    MATCH_ADMIN_TIME_COMING,
    BET_PLAYER_WIN,
    BET_PLAYER_LOSE,
    BET_PLAYER_FORFEIT
}
